# .prettierrc.toml
printWidth = 100
tabWidth = 4
useTabs = false
semi = true 
trailingComma = "all"
singleQuote = false 
bracketSpacing = true
arrowParens = "always"
embeddedLanguageFormatting = "auto"